services:
  bot:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/learn_bot?sslmode=disable
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - MIN_PASS_SCORE=${MIN_PASS_SCORE}
      - SUCCESS_PHOTO=${SUCCESS_PHOTO}
      - FAIL_PHOTO=${FAIL_PHOTO}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learn_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: